image: docker:latest

services:
  - docker:dind
  
stages:
  - build

build-dev:
  stage: build
  script:
    - docker info
    - docker build --pull -t "$CI_REGISTRY/$CI_PROJECT_NAME:dev" .
    - docker push "$CI_REGISTRY/$CI_PROJECT_NAME:dev"
  only:
    - dev
  tags:
    - builder

build-master:
  stage: build
  script:
    - docker info
    - docker build --pull -t "$CI_REGISTRY/$CI_PROJECT_NAME:latest" .
    - docker push "$CI_REGISTRY/$CI_PROJECT_NAME:latest"
  only:
    - master
  tags:
    - builder

build-tag:
  stage: build
  script:
    - IMAGE_TAG=${CI_COMMIT_TAG#v}
    - docker info
    - docker build --pull -t "$CI_REGISTRY/$CI_PROJECT_NAME:$IMAGE_TAG" .
    - docker push "$CI_REGISTRY/$CI_PROJECT_NAME:$IMAGE_TAG"
  only:
    - /^v(\d+\.)?(\d+\.)?(\*|\d+)$/
  tags:
    - builder
